FROM --platform=linux/arm64 golang:1.21-alpine AS builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev alsa-lib-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o tts_service main.go

FROM --platform=linux/arm64 alpine:latest

RUN apk add --no-cache ca-certificates alsa-lib espeak espeak-dev ffmpeg alsa-lib-dev portaudio-dev

RUN mkdir -p /app

COPY --from=builder /app/tts_service /app/tts_service

RUN mkdir -p /shared/audio

CMD ["/app/tts_service"]