FROM golang:1.21-alpine AS builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev alsa-lib-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o tts_service main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates alsa-lib espeak espeak-dev

WORKDIR /root/

COPY --from=builder /app/tts_service .

RUN mkdir -p /shared/audio

RUN apk add --no-cache ffmpeg
RUN apk add --no-cache \
    alsa-lib-dev \
    portaudio-dev \
    espeak \
    espeak-dev

CMD ["./tts_service"]